package gov.cms.fqhc_pricer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Line implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String hcpc;
	private java.lang.String description;
	private java.lang.String modifier;
	private java.util.Date serviceDate;
	private java.lang.String revenueCode;
	private java.lang.Integer totalUnits;
	private java.lang.Integer coveredUnits;
	private java.lang.Double coveredCharges;
	private java.lang.String paymentIndicator;
	private java.lang.String packagingFlag;
	private java.lang.String paymentMethodFlag;
	private java.lang.String lineItemActionFlag;
	private java.lang.String compositeAdjFlag;
	private java.lang.Double linePayment;
	private java.lang.Double lineMedicareReimbursement;
	private java.lang.Double lineCoinsurance;
	private java.lang.Double lineAddonPayment;
	private java.lang.String lineReturnCode;

	public Line() {
	}

	public java.lang.String getHcpc() {
		return this.hcpc;
	}

	public void setHcpc(java.lang.String hcpc) {
		this.hcpc = hcpc;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getModifier() {
		return this.modifier;
	}

	public void setModifier(java.lang.String modifier) {
		this.modifier = modifier;
	}

	public java.lang.String getRevenueCode() {
		return this.revenueCode;
	}

	public void setRevenueCode(java.lang.String revenueCode) {
		this.revenueCode = revenueCode;
	}

	public java.lang.Integer getTotalUnits() {
		return this.totalUnits;
	}

	public void setTotalUnits(java.lang.Integer totalUnits) {
		this.totalUnits = totalUnits;
	}

	public java.lang.Integer getCoveredUnits() {
		return this.coveredUnits;
	}

	public void setCoveredUnits(java.lang.Integer coveredUnits) {
		this.coveredUnits = coveredUnits;
	}

	public java.lang.Double getCoveredCharges() {
		return this.coveredCharges;
	}

	public void setCoveredCharges(java.lang.Double coveredCharges) {
		this.coveredCharges = coveredCharges;
	}

	public java.lang.String getPaymentIndicator() {
		return this.paymentIndicator;
	}

	public void setPaymentIndicator(java.lang.String paymentIndicator) {
		this.paymentIndicator = paymentIndicator;
	}

	public java.lang.String getPackagingFlag() {
		return this.packagingFlag;
	}

	public void setPackagingFlag(java.lang.String packagingFlag) {
		this.packagingFlag = packagingFlag;
	}

	public java.lang.String getPaymentMethodFlag() {
		return this.paymentMethodFlag;
	}

	public void setPaymentMethodFlag(java.lang.String paymentMethodFlag) {
		this.paymentMethodFlag = paymentMethodFlag;
	}

	public java.lang.String getLineItemActionFlag() {
		return this.lineItemActionFlag;
	}

	public void setLineItemActionFlag(java.lang.String lineItemActionFlag) {
		this.lineItemActionFlag = lineItemActionFlag;
	}

	public java.lang.String getCompositeAdjFlag() {
		return this.compositeAdjFlag;
	}

	public void setCompositeAdjFlag(java.lang.String compositeAdjFlag) {
		this.compositeAdjFlag = compositeAdjFlag;
	}

	public java.lang.Double getLinePayment() {
		return this.linePayment;
	}

	public void setLinePayment(java.lang.Double linePayment) {
		this.linePayment = linePayment;
	}

	public java.lang.Double getLineMedicareReimbursement() {
		return this.lineMedicareReimbursement;
	}

	public void setLineMedicareReimbursement(
			java.lang.Double lineMedicareReimbursement) {
		this.lineMedicareReimbursement = lineMedicareReimbursement;
	}

	public java.lang.Double getLineCoinsurance() {
		return this.lineCoinsurance;
	}

	public void setLineCoinsurance(java.lang.Double lineCoinsurance) {
		this.lineCoinsurance = lineCoinsurance;
	}

	public java.lang.Double getLineAddonPayment() {
		return this.lineAddonPayment;
	}

	public void setLineAddonPayment(java.lang.Double lineAddonPayment) {
		this.lineAddonPayment = lineAddonPayment;
	}

	public java.lang.String getLineReturnCode() {
		return this.lineReturnCode;
	}

	public void setLineReturnCode(java.lang.String lineReturnCode) {
		this.lineReturnCode = lineReturnCode;
	}

	public java.util.Date getServiceDate() {
		return this.serviceDate;
	}

	public void setServiceDate(java.util.Date serviceDate) {
		this.serviceDate = serviceDate;
	}

}